// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

const (
	Api_keyScopes = "api_key.Scopes"
)

// Order defines model for Order.
type Order struct {
	Id    *string `json:"id,omitempty"`
	Items *[]struct {
		// ProductId ID of the product
		ProductId *string `json:"productId,omitempty"`

		// Quantity Item count
		Quantity *int `json:"quantity,omitempty"`
	} `json:"items,omitempty"`
	Products *[]Product `json:"products,omitempty"`
}

// OrderReq Place a new order
type OrderReq struct {
	// CouponCode Optional promo code applied to the order
	CouponCode *string `json:"couponCode,omitempty"`
	Items      []struct {
		// ProductId ID of the product (required)
		ProductId string `json:"productId"`

		// Quantity Item count (required)
		Quantity int `json:"quantity"`
	} `json:"items"`
}

// Product defines model for Product.
type Product struct {
	Category *string `json:"category,omitempty"`
	Id       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`

	// Price Selling price
	Price *float32 `json:"price,omitempty"`
}

// PlaceOrderJSONRequestBody defines body for PlaceOrder for application/json ContentType.
type PlaceOrderJSONRequestBody = OrderReq
